import logging
import numpy as np
import pandas as pd
from scipy import stats
from datetime import datetime
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class StatisticalValidator:
    """
    Full hedge-fund validation toolkit for any candidate signal.

    Runs nine independent tests and synthesises a verdict:
      STRONG_APPROVE / APPROVE / INVESTIGATE / REJECT
    """

    def __init__(self, config: dict):
        self.min_sharpe_oos = 0.8
        self.min_win_rate = 0.52
        self.apply_bonferroni: bool = config.get("altdata", {}).get(
            "bonferroni_correction", True
        )

    # ------------------------------------------------------------------
    # Main validation entry point
    # ------------------------------------------------------------------

    def validate(
        self,
        signal_returns: pd.Series,
        n_hypotheses_tested: int = 1,
        signal_metadata: dict = None,
    ) -> Dict:
        """
        Run the full validation suite on a series of signal returns.

        Parameters
        ----------
        signal_returns        : pd.Series of per-period returns generated by the signal
        n_hypotheses_tested   : total number of hypotheses tested (for multiple-testing correction)
        signal_metadata       : optional dict, e.g. {"n_params": 3}

        Returns
        -------
        dict with per-test results and an overall verdict:
          STRONG_APPROVE  — all core tests pass, Sharpe >= 1.2
          APPROVE         — all core tests pass
          INVESTIGATE     — core tests pass but secondary tests flag concerns
          REJECT          — one or more core tests fail
        """
        r = signal_returns.dropna()
        if len(r) < 100:
            return {"verdict": "REJECT", "reason": "insufficient_data", "n": len(r)}

        results: Dict = {}

        # 1. T-test (one-sample, H0: mean = 0) -------------------------
        t_stat, p_val = stats.ttest_1samp(r, 0)
        p_adj = (
            min(p_val * n_hypotheses_tested, 1.0)
            if self.apply_bonferroni
            else p_val
        )
        results["ttest"] = {
            "t": float(t_stat),
            "p": float(p_val),
            "p_bonferroni": float(p_adj),
            "passed": bool(p_adj < 0.05 and t_stat > 0),
        }

        # 2. Sharpe ratio (annualised) ---------------------------------
        sharpe = (
            float((r.mean() / r.std()) * np.sqrt(252)) if r.std() > 0 else 0.0
        )
        results["sharpe"] = {
            "value": sharpe,
            "passed": sharpe >= self.min_sharpe_oos,
        }

        # 3. Win rate --------------------------------------------------
        win_rate = float((r > 0).mean())
        results["win_rate"] = {
            "value": win_rate,
            "passed": win_rate >= self.min_win_rate,
        }

        # 4. Benjamini-Hochberg FDR correction -------------------------
        if n_hypotheses_tested > 1:
            bh_threshold = 0.05 * 1 / n_hypotheses_tested  # simplified BH
            results["bh_fdr"] = {
                "threshold": bh_threshold,
                "passed": bool(p_val < bh_threshold),
            }
        else:
            results["bh_fdr"] = {"passed": True}

        # 5. Regime stability ------------------------------------------
        results["regime_stability"] = self._regime_stability(r)

        # 6. Monte Carlo permutation test ------------------------------
        results["permutation"] = self._permutation_test(r)

        # 7. Deflated Sharpe Ratio (Bailey & Lopez de Prado 2014) ------
        dsr = self._deflated_sharpe(r, sharpe, n_hypotheses_tested)
        results["deflated_sharpe"] = {
            "value": float(dsr),
            "passed": dsr >= 0.5,
        }

        # 8. Decay projection ------------------------------------------
        results["decay"] = self._decay_projection(r)

        # 9. MDL (Minimum Description Length) — penalise by complexity -
        n_params = (
            (signal_metadata or {}).get("n_params", 1)
        )
        mdl_penalty = np.log(len(r)) * n_params / 2
        mdl_passed = bool(sharpe * len(r) > mdl_penalty)
        results["mdl"] = {
            "penalty": float(mdl_penalty),
            "passed": mdl_passed,
        }

        # Overall verdict ----------------------------------------------
        core_passed = (
            results["ttest"]["passed"]
            and results["sharpe"]["passed"]
            and results["win_rate"]["passed"]
            and results["permutation"]["passed"]
            and results["deflated_sharpe"]["passed"]
        )

        secondary_passed = (
            results["regime_stability"].get("n_positive_regimes", 0) >= 2
            and results["decay"].get("months_to_zero", 12) >= 6
        )

        if core_passed and secondary_passed:
            verdict = "STRONG_APPROVE" if sharpe >= 1.2 else "APPROVE"
        elif core_passed:
            verdict = "INVESTIGATE"
        else:
            verdict = "REJECT"

        logger.info(
            "StatisticalValidator verdict: %s (sharpe=%.2f dsr=%.3f n=%d)",
            verdict,
            sharpe,
            dsr,
            len(r),
        )
        return {
            "verdict": verdict,
            "sharpe": sharpe,
            "dsr": float(dsr),
            "tests": results,
            "n": len(r),
        }

    # ------------------------------------------------------------------
    # Individual tests
    # ------------------------------------------------------------------

    def _regime_stability(self, r: pd.Series) -> dict:
        """
        Split history into 3 equal regimes and compute Sharpe in each.
        Passes if at least 2 out of 3 regimes have positive Sharpe.
        """
        n = len(r)
        regimes = {
            "pre_2020": r.iloc[: n // 3],
            "2020_2022": r.iloc[n // 3 : 2 * n // 3],
            "2022_present": r.iloc[2 * n // 3 :],
        }
        sharpes: Dict[str, float] = {}
        for regime_name, ret in regimes.items():
            if ret.std() > 0:
                sharpes[regime_name] = float(
                    (ret.mean() / ret.std()) * np.sqrt(252)
                )
            else:
                sharpes[regime_name] = 0.0

        n_positive = sum(1 for s in sharpes.values() if s > 0)
        return {
            "regime_sharpes": sharpes,
            "n_positive_regimes": n_positive,
            "passed": n_positive >= 2,
        }

    def _permutation_test(self, r: pd.Series, n_shuffles: int = 1000) -> dict:
        """
        Monte Carlo permutation test.
        Passes if observed Sharpe is above the 95th percentile of the
        null distribution obtained by randomly shuffling returns.
        """
        if r.std() == 0:
            return {"passed": False, "reason": "zero_variance"}

        observed_sharpe = float(r.mean() / r.std() * np.sqrt(252))
        rng = np.random.default_rng(0)
        null_sharpes: List[float] = []
        arr = r.values

        for _ in range(n_shuffles):
            perm = rng.permutation(arr)
            s = pd.Series(perm)
            if s.std() > 0:
                null_sharpes.append(float(s.mean() / s.std() * np.sqrt(252)))

        if not null_sharpes:
            return {"passed": False}

        threshold = float(np.percentile(null_sharpes, 95))
        return {
            "threshold": threshold,
            "observed": observed_sharpe,
            "passed": observed_sharpe > threshold,
        }

    def _deflated_sharpe(
        self, r: pd.Series, sharpe: float, n_trials: int
    ) -> float:
        """
        Bailey & Lopez de Prado (2014) Deflated Sharpe Ratio.

        Adjusts the observed Sharpe for non-normality of returns and the
        number of trials (multiple-testing bias), returning the probability
        that the true Sharpe is positive.
        """
        T = len(r)
        if T <= 1:
            return 0.0

        skew = float(r.skew())
        kurt = float(r.kurtosis())

        # Expected maximum Sharpe under the null (Bailey & Lopez de Prado eq. 8)
        if n_trials > 1:
            e_max_sr = (
                (1 - 0.5772) * stats.norm.ppf(1 - 1 / n_trials)
                + 0.5772 * stats.norm.ppf(1 - 1 / (n_trials * np.e))
            )
        else:
            e_max_sr = 0.0

        denom_inner = 1 - skew * sharpe + (kurt / 4) * sharpe ** 2
        if denom_inner <= 0:
            return 0.0

        denom = np.sqrt(denom_inner) / np.sqrt(T - 1)
        if denom == 0:
            return 0.0

        dsr = float(stats.norm.cdf((sharpe - e_max_sr) / denom))
        return dsr

    def _decay_projection(self, r: pd.Series) -> dict:
        """
        Fit a linear trend to rolling Sharpe over time.

        Returns an estimate of how many months until the signal decays to zero.
        Passes if projected months_to_zero >= 6.
        """
        window = max(20, len(r) // 10)
        rolling_sharpe = r.rolling(window).apply(
            lambda x: float(x.mean() / x.std() * np.sqrt(252))
            if x.std() > 0
            else 0.0,
            raw=True,
        ).dropna()

        if len(rolling_sharpe) < 10:
            return {"months_to_zero": 999, "passed": True}

        x = np.arange(len(rolling_sharpe))
        y = rolling_sharpe.values
        slope, intercept, *_ = stats.linregress(x, y)

        if slope >= 0 or intercept <= 0:
            return {
                "months_to_zero": 999,
                "slope": float(slope),
                "passed": True,
            }

        periods_to_zero = -intercept / slope
        # Each period is `window` trading days; ~21 trading days per month
        months_to_zero = float(periods_to_zero * window / 21)

        return {
            "months_to_zero": months_to_zero,
            "slope": float(slope),
            "classification": (
                "SHORT_LIVED" if months_to_zero < 6 else "DURABLE"
            ),
            "passed": months_to_zero >= 6,
        }
